name: Manual full deploy to Dokku (via VPN)

on:
  workflow_dispatch:   # allows triggering manually in GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: VPN Connect
        uses: igdevx/l2tp-ipsec-vpn-action@v2
        id: vpn
        with:
          vpn_gateway: ${{ secrets.VPN_GATEWAY }}
          vpn_psk: ${{ secrets.VPN_PSK }}
          vpn_username: ${{ secrets.VPN_USERNAME }}
          vpn_password: ${{ secrets.VPN_PASSWORD }}
          vpn_nt_domain: ${{ secrets.VPN_NT_DOMAIN }}
          vpn_ike: ${{ secrets.VPN_IKE }}
          vpn_esp: ${{ secrets.VPN_ESP }}
      
      - name: VPN route IP setup
        run: |
          HOST_IP=$(nslookup ${{ secrets.DOKKU_HOST }} | awk '/^Address: / { print $2 }' | tail -n1)
          IFACE="${{ steps.vpn.outputs.ppp_interface }}"

          sudo ip route add "$HOST_IP" dev "$IFACE"
      
      - name: SSH key setup
        run: |
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/id_ed25519
          ${{ secrets.DOKKU_SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.DOKKU_HOST }}" >> ~/.ssh/known_hosts || { echo "❌ ssh-keyscan failed"; exit 1; }

      - name: Deploy all services
        run: |
          echo "🔹 Deploying all services from manifest..."
          
          MANIFEST=$(yq eval -o=json '.services' deployment-manifest.yaml)
          for service in $(echo "$MANIFEST" | jq -r 'keys[]'); do
            IMAGE=$(echo "$MANIFEST" | jq -r ".\"$service\"")
            
            echo "🔄 Deploying $service from $IMAGE ..."
            
            OUTPUT=$(ssh dokku@${{ secrets.DOKKU_HOST }} git:from-image "$service" "$IMAGE" 2>&1) || true
            
            if echo "$OUTPUT" | grep -q "ps:rebuild"; then
              echo "ℹ️ $service already exists — rebuilding instead..."
              ssh dokku@${{ secrets.DOKKU_HOST }} ps:rebuild "$service"
              echo "✅ Rebuild complete!"
            else
              echo "⚠️ Deployment failed — app likely doesn't exist. Creating it..."
              ssh dokku@${{ secrets.DOKKU_HOST }} apps:create "$service"
              echo "🔁 Retrying deployment..."
              ssh dokku@${{ secrets.DOKKU_HOST }} git:from-image "$service" "$IMAGE"
              echo "✅ Deployment complete!"
            fi
          done

          echo "✅ All services deployed!"